import"./assets/styles-CwD8JiEY.js";import{a as s,i as u}from"./assets/vendor-4yCzdkXl.js";const a={page:1,increasePage(t){a.page+=1},setFirstPage(){a.page=1},category:null,setCategory(t){a.category=t},api:null,setApi(t){a.api=t}},r={categories:document.querySelector(".categories"),products:document.querySelector(".products"),input:document.querySelector(".search-form__input"),form:document.querySelector(".search-form"),notFound:document.querySelector(".not-found"),modalProduct:document.querySelector(".modal-product"),modalWindow:document.querySelector(".modal"),modalCloseBtn:document.querySelector(".modal__close-btn"),main:document.getElementsByTagName("main")[0]};function b(){r.products.innerHTML=""}function L(){r.main.insertAdjacentHTML("beforeEnd",'<button class="load-more-btn" type="button">Load more</button>'),r.loadMoreBtn=document.querySelector(".load-more-btn"),r.loadMoreBtn.addEventListener("click",A)}function d(){r.loadMoreBtn&&r.loadMoreBtn.remove()}s.defaults.baseURL="https://dummyjson.com/products";async function v(){try{return await s.get("/category-list").then(o=>o.data)}catch(t){console.log(`fetch categories ${t}`)}}async function y(t=a.page){try{const o=await s.get(`?limit=12&skip=${(t-1)*12}`).then(e=>e.data);return a.setApi(1),o}catch(o){console.log(`fetch all products ${o}`)}}async function f(t){try{return await s.get(`${t}`).then(e=>e.data)}catch(o){console.log(`fetch products by id ${o}`)}}async function p(t){try{return await s.get(`search?q=${t}`).then(e=>e.data)}catch(o){console.log(`fetch products by query ${o}`)}}async function _(t=a.page,o){try{const e=await s.get(`category/${o}?limit=12&skip=${(t-1)*12}`).then(c=>c.data);return a.setApi(2),e}catch(e){console.log(`fetch products by category ${e}`)}}function P(){r.modalWindow.addEventListener("click",$),r.modalCloseBtn.addEventListener("click",i),document.addEventListener("keydown",h)}function k(){r.modalWindow.removeEventListener("click",$),r.modalCloseBtn.removeEventListener("click",i),document.removeEventListener("keydown",h)}function C(){r.modalWindow.classList.add("modal--is-open"),P()}function i(){r.modalWindow.classList.remove("modal--is-open"),k()}function h(t){if(t.key==="Escape")i();else return}function $(t){if(t.target===r.modalWindow)i();else return}async function E(t){try{t.innerHTML="";const e=(await v()).map(c=>`<li class="categories__item">
 <button class="categories__btn" type="button">${c}</button>
</li>`).join("");t.insertAdjacentHTML("beforeEnd",e)}catch(o){console.log(`render categories ${o}`)}}async function l(t,o){try{o.innerHTML="";const e=await t,c=e.products.map(n=>`<li class="products__item" data-id="${n.id}">
    <img class="products__image" src="${n.thumbnail}" alt="${n.title}"/>
    <p class="products__title">${n.title}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand: ${n.brand}</span></p>
    <p class="products__category">Category: ${n.category}</p>
    <p class="products__price">Price: ${n.price}$</p>
 </li>`).join("");o.insertAdjacentHTML("beforeEnd",c),e.total>12&&!document.querySelector(".load-more-btn")?L():d()}catch(e){console.log(`render products ${e}`)}}async function M(t,o){try{t.innerHTML="";const e=await f(o),c=`<img class="modal-product__img" src="${e.thumbnail}" alt="${e.title}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${e.title}</p>
        <ul class="modal-product__tags">${e.tags}</ul>
        <p class="modal-product__description">${e.description}</p>
        <p class="modal-product__shipping-information">Shipping: ${e.shippingInformation}</p>
        <p class="modal-product__return-policy">Return Policy: ${e.returnPolicy}</p>
        <p class="modal-product__price">Price: ${e.price}$</p>
      </div>`;t.insertAdjacentHTML("beforeEnd",c),C()}catch(e){console.log(`render products ${e}`)}}function m(t,o){const e=t.products.map(c=>`<li class="products__item" data-id="${c.id}">
    <img class="products__image" src="${c.thumbnail}" alt="${c.title}"/>
    <p class="products__title">${c.title}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand: ${c.brand}</span></p>
    <p class="products__category">Category: ${c.category}</p>
    <p class="products__price">Price: ${c.price}$</p>
 </li>`).join("");o.insertAdjacentHTML("beforeEnd",e)}function S(t,o){localStorage.setItem(t,JSON.stringify(o))}function g(t){try{return JSON.parse(localStorage.getItem(t))}catch(o){console.log(`load from local storage ${o}`)}}function w(t){localStorage.removeItem(t)}function B(t){r.notFound.classList.remove("not-found--visible"),t.preventDefault();const o=r.input.value.trim();w("searchKey");try{p(o).then(e=>{e.products.length>0?l(p(o),r.products):(b(),r.notFound.classList.add("not-found--visible"))})}catch(e){console.log(`searchProducts ${e}`)}r.input.value=""}function q(){S("searchKey",r.input.value)}function T(t){t.target.classList.contains("categories__btn")&&(d(),a.setFirstPage(),a.setCategory(t.target.textContent),l(_(a.page,t.target.textContent),r.products))}function j(t){const o=t.target.closest(".products__item");if(o&&r.products.contains(o)){const e=o.dataset.id;M(r.modalProduct,e)}else return}async function A(){a.increasePage();try{if(a.api===1){const t=await y();m(t,r.products),t.total-t.skip<12&&(d(),u.info({message:"You reached the end of list",position:"bottomCenter"}))}else if(a.api===2){const t=await _(a.page,a.category);m(t,r.products),console.log(t),t.total-t.skip<12&&(d(),u.info({message:"You reached the end of list",position:"bottomCenter"}))}}catch(t){console.log(`load more ${t}`)}}E(r.categories);l(y(1),r.products);r.input.value=g("searchKey")?g("searchKey"):"";r.input.addEventListener("input",q);r.form.addEventListener("submit",B);r.categories.addEventListener("click",T);f(2);r.products.addEventListener("click",j);
//# sourceMappingURL=index.js.map
